In [11]:
#Q-1
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#Q-2
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
#Q-3
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Q-4
y = np.nonzero([1,2,0,0,4,0])
print(y)

(array([0, 1, 4], dtype=int64),)


In [21]:
#Q-5
s = np.random.random((10,10))
s_min = s.min()
print(s_min)
s_max = s.max()
print(s_max)

0.00196935207968163
0.9809068011499796


In [22]:
#Q-6
d= np.random.random(30)
f = d.mean()
print(f)

0.6088542562565417
